#!/bin/bash

#look for current path of program, even if symlinked
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; 
do 
	# resolve $SOURCE until the file is no longer a symlink
	DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
	SOURCE="$(readlink "$SOURCE")"
	[[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done

MYSNAP_APP_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

#start java
java -classpath "$MYSNAP_APP_DIR/bin:$MYSNAP_APP_DIR/lib/commons-cli-1.2.jar" de.anselm.main.Main $@
